language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - allowed_dupes=spacemacs,ace-jump-mode,ternjs,emacs-evil/evil,awesome.re
  - awesome_bot README.org --white-list $allowed_dupes
