language: ruby
rvm:
  - 2.4
before_script:
  - gem install awesome_bot
script:
  - allowed_internal_links=ternjs
  - allowed_redirect_links=awesome.re
  - awesome_bot README.org --white-list $allowed_internal_links,$allowed_redirect_links
