sudo: required
language: emacs-lisp
services:
  - docker
script:
  - allowed_internal_links=ternjs,melpa
  - allowed_redirect_links=awesome.re
  - #awesome_bot README.org --allow-ssl --white-list $allowed_internal_links,$allowed_redirect_links
  - cp README.org README.org.original

  - setupEmacsPackageArchives="(setq package-archives '((\\\"melpa\\\" . \\\"https://melpa.org/packages/\\\"))) (package-initialize)"
  - #installTocOrgPackage="(when (not (package-installed-p 'toc-org)) (when (not package-archive-contents) (package-refresh-contents)) (package-install 'toc-org)) (require 'toc-org)"
  - installTocOrgPackage="(package-refresh-contents) (package-install 'toc-org) (require 'toc-org)"
  - runTocOrgInsertTocFunction="(toc-org-insert-toc) (save-buffer) (kill-emacs)"

  - emacsExpression="(progn $setupEmacsPackageArchives $installTocOrgPackage $runTocOrgInsertTocFunction)"
  - pwd
  - echo '$HOME'
  - echo $HOME
  - echo '$PWD'
  - echo $PWD
  - echo '$PATH'
  - echo $PATH
  - ls -la
  - mkdir $HOME/.emacs.d
  - EMACS_PACKAGES="toc-org"
  - docker run -ti --rm \
           -v ${HOME}:${HOME} \
           -v $HOME/.emacs.d:/root/.emacs.d \
           -w ${PWD} \
           iquiw/alpine-emacs \
           README.org --eval "(require 'toc-org) (toc-org-insert-toc) (save-buffer) (kill-emacs)"


  - diff README.org README.org.original
  - echo "If the README pre and post processing are identical, the diff should exit with 0. Otherwise, an error code indicates that toc-org should have been run to update the Table of Contents."

notifications:
  email:
    on_success: never
    on_failure: never



