services:
  - docker

before-install:
  - docker pull dkhamsing/awesome_bot 
  - docker ps -a

script:
  - allowed_internal_links=ternjs,melpa
  - allowed_redirect_links=awesome.re
  - cp README.org README.org.original
  - diff README.org README.org.original
  - echo "cat README.org"
  #- cat README.org
  - docker run -ti --rm -v $PWD:/mnt:rw dkhamsing/awesome_bot README.org --allow-ssl --white-list $allowed_internal_links,$allowed_redirect_links

notifications:
  email:
    on_success: never
    on_failure: never
