language: ruby
rvm:
  - 2.4
before_script:
  - gem install awesome_bot
script:
  - allowed_dupes=ace-jump-mode,awesome.re,emacs-evil/evil,guide-key,spacemacs,ternjs
  - awesome_bot README.org --white-list $allowed_dupes
