sudo: false
language: ruby
rvm:
  - 2.4
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
  - EMACS_VERSION=25.3
install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
before_script:
  - gem install awesome_bot
script:

  - allowed_internal_links=ternjs
  - allowed_redirect_links=awesome.re
  - awesome_bot README.org --white-list $allowed_internal_links,$allowed_redirect_links

  - sh -c "sed -i 's@ (interactive)@ ;;(interactive)@' gen-toc.el"
  - cp README.org README.org.original
  # https://stackoverflow.com/questions/18033190/start-emacs-from-shell-with-predefined-lisp-code
  - $EMACS README.org -Q -nw --load gen-toc.el --eval '(progn (awesome-emacs-gen-toc)(save-buffer)(kill-emacs))'
  - diff README.org README.org.original
  - echo "If the README pre and post processing are identical, the diff should exit with 0. Otherwise, an error code indicates that gen-toc.el should have been run to update the Table of Contents."
  #- export DIFFOUTPUT="$(diff README.org README.org.original  2>&1 )"
  #- echo $DIFFOUTPUT
  #- sh -c "[ ! -z $DIFFOUTPUT ] && echo 'The Table of Contents should have been updated. Run gen-toc.el and update README.org .'"
  #- sh -c "(test ! -z $DIFFOUTPUT) && echo 'The Table of Contents should have been updated. Run gen-toc.el and update README.org'"

notifications:
  email:
    on_success: never
    on_failure: never
